### ISSUE TITLE
Moderator must be able to manage related events

### ISSUE THREAD

**Issue by ReneProgramming** [ReneProgramming/AnimeFanWeb#1]
Moderators should have full CRUD functionality for courses

- [ ]  Add moderator Role
- [ ] Moderators can Create an event (Date/Time/Place)
- [ ] Moderators can Edit an event
- [ ] Moderators can Delete an event
- [ ] Moderators can have a landing page to display all events
- [ ] Only Moderators can Edit/Delete/Create courses
